// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.TrustedForm.Certificates.OpenApiClient.Models
{
    /// <summary>
    /// The `advertiser_name` parameter is optional but is required to populate the `one_to_one` property.The `advertiser_name` parameter only applies to the One to One Consent value (returned as `one_to_one`). It has no effect onany other values returned by the Verify call.The `min_font_size_px_required`, `min_contrast_ratio_required`, and `opt_in_types_allowed` parameters are optional.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VerifyParameters : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The name of the legal entity for an advertiser, used to determine if they were given consent in a one-to-one manner. Normalized to be case-insensitive, ignore extra spaces, and omit non-alphanumeric characters (e.g., “Acme Inc.” and “acme inc” are the same). This value can be passed in the request or set via the [verification criteria page](https://app.trustedform.com/verification_criteria) and will appear in the response if provided in either.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdvertiserName { get; set; }
#nullable restore
#else
        public string AdvertiserName { get; set; }
#endif
        /// <summary>The number indicating the minimum contrast ratio required between the consent language text and background. This value can be passed in the request or set via the [verification criteria page](https://app.trustedform.com/verification_criteria) and will appear in the response if provided in either.</summary>
        public double? MinContrastRatioRequired { get; set; }
        /// <summary>The number indicating the minimum font size required for the consent language. This value can be passed in the request or set via the [verification criteria page](https://app.trustedform.com/verification_criteria) and will appear in the response if provided in either.</summary>
        public double? MinFontSizePxRequired { get; set; }
        /// <summary>An array of strings that lists the opt-in types that are allowed. This value can be passed in the request or set via the [verification criteria page](https://app.trustedform.com/verification_criteria) and will appear in the response if provided through either method. The array can include one or more of the following values:- `manual`: The consumer actively checked a box to provide consent.- `pre-selected`: An opt-in field was selected by default, without explicit action from the consumer.- `non-interactive`: In the absence of an opt-in field, the consumer gave consent by submitting the form.This field is used to define which opt-in types are considered valid.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.VerifyParameters_opt_in_types_allowed?>? OptInTypesAllowed { get; set; }
#nullable restore
#else
        public List<global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.VerifyParameters_opt_in_types_allowed?> OptInTypesAllowed { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.VerifyParameters"/> and sets the default values.
        /// </summary>
        public VerifyParameters()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.VerifyParameters"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.VerifyParameters CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.VerifyParameters();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "advertiser_name", n => { AdvertiserName = n.GetStringValue(); } },
                { "min_contrast_ratio_required", n => { MinContrastRatioRequired = n.GetDoubleValue(); } },
                { "min_font_size_px_required", n => { MinFontSizePxRequired = n.GetDoubleValue(); } },
                { "opt_in_types_allowed", n => { OptInTypesAllowed = n.GetCollectionOfEnumValues<global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.VerifyParameters_opt_in_types_allowed>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("advertiser_name", AdvertiserName);
            writer.WriteDoubleValue("min_contrast_ratio_required", MinContrastRatioRequired);
            writer.WriteDoubleValue("min_font_size_px_required", MinFontSizePxRequired);
            writer.WriteCollectionOfEnumValues<global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.VerifyParameters_opt_in_types_allowed>("opt_in_types_allowed", OptInTypesAllowed);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
