// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.TrustedForm.Certificates.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum VerifyResult_opt_in_types_allowed
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "manual")]
        #pragma warning disable CS1591
        Manual,
        #pragma warning restore CS1591
        [EnumMember(Value = "pre-selected")]
        #pragma warning disable CS1591
        PreSelected,
        #pragma warning restore CS1591
        [EnumMember(Value = "non-interactive")]
        #pragma warning disable CS1591
        NonInteractive,
        #pragma warning restore CS1591
    }
}
