// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.TrustedForm.Certificates.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WebInsightsResult_properties_form_input_method
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "autofill")]
        #pragma warning disable CS1591
        Autofill,
        #pragma warning restore CS1591
        [EnumMember(Value = "paste")]
        #pragma warning disable CS1591
        Paste,
        #pragma warning restore CS1591
        [EnumMember(Value = "typing")]
        #pragma warning disable CS1591
        Typing,
        #pragma warning restore CS1591
        [EnumMember(Value = "pre-populated")]
        #pragma warning disable CS1591
        PrePopulated,
        #pragma warning restore CS1591
    }
}
