// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.TrustedForm.Certificates.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MetaLeadAdsInsightsResult"/>, <see cref="global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MobileInsightsResult"/>, <see cref="global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.WebInsightsResult"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InsightsResult : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MetaLeadAdsInsightsResult"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MetaLeadAdsInsightsResult? MetaLeadAdsInsightsResult { get; set; }
#nullable restore
#else
        public global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MetaLeadAdsInsightsResult MetaLeadAdsInsightsResult { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MobileInsightsResult"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MobileInsightsResult? MobileInsightsResult { get; set; }
#nullable restore
#else
        public global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MobileInsightsResult MobileInsightsResult { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.WebInsightsResult"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.WebInsightsResult? WebInsightsResult { get; set; }
#nullable restore
#else
        public global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.WebInsightsResult WebInsightsResult { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.InsightsResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.InsightsResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.InsightsResult();
            if("MetaLeadAdsInsightsResult".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MetaLeadAdsInsightsResult = new global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MetaLeadAdsInsightsResult();
            }
            else if("MobileInsightsResult".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MobileInsightsResult = new global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MobileInsightsResult();
            }
            else if("WebInsightsResult".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WebInsightsResult = new global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.WebInsightsResult();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(MetaLeadAdsInsightsResult != null)
            {
                return MetaLeadAdsInsightsResult.GetFieldDeserializers();
            }
            else if(MobileInsightsResult != null)
            {
                return MobileInsightsResult.GetFieldDeserializers();
            }
            else if(WebInsightsResult != null)
            {
                return WebInsightsResult.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(MetaLeadAdsInsightsResult != null)
            {
                writer.WriteObjectValue<global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MetaLeadAdsInsightsResult>(null, MetaLeadAdsInsightsResult);
            }
            else if(MobileInsightsResult != null)
            {
                writer.WriteObjectValue<global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MobileInsightsResult>(null, MobileInsightsResult);
            }
            else if(WebInsightsResult != null)
            {
                writer.WriteObjectValue<global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.WebInsightsResult>(null, WebInsightsResult);
            }
        }
    }
}
#pragma warning restore CS0618
