// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.TrustedForm.Certificates.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum InsightsParameters_properties
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "age_seconds")]
        #pragma warning disable CS1591
        Age_seconds,
        #pragma warning restore CS1591
        [EnumMember(Value = "approx_ip_geo")]
        #pragma warning disable CS1591
        Approx_ip_geo,
        #pragma warning restore CS1591
        [EnumMember(Value = "bot_detected")]
        #pragma warning disable CS1591
        Bot_detected,
        #pragma warning restore CS1591
        [EnumMember(Value = "confirmed_owner")]
        #pragma warning disable CS1591
        Confirmed_owner,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        Created_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "domain")]
        #pragma warning disable CS1591
        Domain,
        #pragma warning restore CS1591
        [EnumMember(Value = "expires_at")]
        #pragma warning disable CS1591
        Expires_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "form_input_kpm")]
        #pragma warning disable CS1591
        Form_input_kpm,
        #pragma warning restore CS1591
        [EnumMember(Value = "form_input_method")]
        #pragma warning disable CS1591
        Form_input_method,
        #pragma warning restore CS1591
        [EnumMember(Value = "form_input_wpm")]
        #pragma warning disable CS1591
        Form_input_wpm,
        #pragma warning restore CS1591
        [EnumMember(Value = "ip")]
        #pragma warning disable CS1591
        Ip,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_framed")]
        #pragma warning disable CS1591
        Is_framed,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_masked")]
        #pragma warning disable CS1591
        Is_masked,
        #pragma warning restore CS1591
        [EnumMember(Value = "num_sensitive_content_elements")]
        #pragma warning disable CS1591
        Num_sensitive_content_elements,
        #pragma warning restore CS1591
        [EnumMember(Value = "num_sensitive_form_elements")]
        #pragma warning disable CS1591
        Num_sensitive_form_elements,
        #pragma warning restore CS1591
        [EnumMember(Value = "os")]
        #pragma warning disable CS1591
        Os,
        #pragma warning restore CS1591
        [EnumMember(Value = "page_url")]
        #pragma warning disable CS1591
        Page_url,
        #pragma warning restore CS1591
        [EnumMember(Value = "parent_page_url")]
        #pragma warning disable CS1591
        Parent_page_url,
        #pragma warning restore CS1591
        [EnumMember(Value = "seconds_on_page")]
        #pragma warning disable CS1591
        Seconds_on_page,
        #pragma warning restore CS1591
    }
}
