// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.TrustedForm.Certificates.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadEmailParameters"/>, <see cref="global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadPhoneEmailParameters"/>, <see cref="global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadPhoneParameters"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MatchLeadParameters : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadEmailParameters"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadEmailParameters? MatchLeadEmailParameters { get; set; }
#nullable restore
#else
        public global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadEmailParameters MatchLeadEmailParameters { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadPhoneEmailParameters"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadPhoneEmailParameters? MatchLeadPhoneEmailParameters { get; set; }
#nullable restore
#else
        public global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadPhoneEmailParameters MatchLeadPhoneEmailParameters { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadPhoneParameters"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadPhoneParameters? MatchLeadPhoneParameters { get; set; }
#nullable restore
#else
        public global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadPhoneParameters MatchLeadPhoneParameters { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadParameters"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadParameters CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadParameters();
            result.MatchLeadEmailParameters = new global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadEmailParameters();
            result.MatchLeadPhoneEmailParameters = new global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadPhoneEmailParameters();
            result.MatchLeadPhoneParameters = new global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadPhoneParameters();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(MatchLeadEmailParameters != null || MatchLeadPhoneEmailParameters != null || MatchLeadPhoneParameters != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(MatchLeadEmailParameters, MatchLeadPhoneEmailParameters, MatchLeadPhoneParameters);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.TrustedForm.Certificates.OpenApiClient.Models.MatchLeadEmailParameters>(null, MatchLeadEmailParameters, MatchLeadPhoneEmailParameters, MatchLeadPhoneParameters);
        }
    }
}
#pragma warning restore CS0618
